/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.Serializable;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Category;
import io.swagger.client.model.Pagination;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Categories
 */


public class Categories implements Serializable {
  @SerializedName("categories")
  private List<Category> categories = null;

  @SerializedName("categories_pagination")
  private Pagination categoriesPagination = null;

  public Categories categories(List<Category> categories) {
    this.categories = categories;
    return this;
  }

  public Categories addCategoriesItem(Category categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<Category>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @Schema(description = "")
  public List<Category> getCategories() {
    return categories;
  }

  public void setCategories(List<Category> categories) {
    this.categories = categories;
  }

  public Categories categoriesPagination(Pagination categoriesPagination) {
    this.categoriesPagination = categoriesPagination;
    return this;
  }

   /**
   * Get categoriesPagination
   * @return categoriesPagination
  **/
  @Schema(description = "")
  public Pagination getCategoriesPagination() {
    return categoriesPagination;
  }

  public void setCategoriesPagination(Pagination categoriesPagination) {
    this.categoriesPagination = categoriesPagination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Categories categories = (Categories) o;
    return Objects.equals(this.categories, categories.categories) &&
        Objects.equals(this.categoriesPagination, categories.categoriesPagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categories, categoriesPagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Categories {\n");
    
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    categoriesPagination: ").append(toIndentedString(categoriesPagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
